app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(api = "aspirin", timeout_ = 10)
app$setInputs(start_date = "2004-01-15")
app$setInputs(end_date = "2021-02-28")
app$setInputs(seriousness = "1")
app$setInputs(submit = "click")
Sys.sleep(2) # sleeping past notifications
app$snapshotDownload("download_data")
app$snapshot()
app$setInputs(api = "tylenol")
app$setInputs(submit = "click")
Sys.sleep(2) # sleeping past notifications
app$snapshot()
app$setInputs(api = "aspirin")
app$setInputs(start_date = "2004-01-16")
app$setInputs(start_date = "2004-01-15")
app$setInputs(seriousness = "2")
app$setInputs(seriousness = "1")
