app <- ShinyDriver$new("../../", seed = 23)
app$snapshotInit("mytest")

app$setInputs(start_date = "2004-01-02", values_=FALSE, wait_=FALSE)
app$setInputs(end_date = "2018-02-15", values_=FALSE, wait_=FALSE)
app$snapshot()
app$setInputs(api = "ibuprofen", values_=FALSE, wait_=FALSE)
app$setInputs(start_date = "2004-01-14", values_=FALSE, wait_=FALSE)
app$setInputs(end_date = "2018-01-31", values_=FALSE, wait_=FALSE)
app$setInputs(seriousness = "1", values_=FALSE, wait_=FALSE)
app$snapshot()
app$setInputs(end_date = "2017-12-31", values_=FALSE, wait_=FALSE)
app$setInputs(seriousness = "2", values_=FALSE, wait_=FALSE)
app$snapshotDownload("download_data")
app$snapshot()
