app <- ShinyDriver$new("../../", seed = 5453)
app$snapshotInit("philstest")

app$setInputs(seriousness = "1")
app$setInputs(seriousness = "2")
app$setInputs(api = "ASPIRIN")
app$setInputs(start_date = "2010-01-01")
app$setInputs(end_date = "2018-01-01")
app$setInputs(seriousness = "0")
app$setInputs(seriousness = "1")
app$snapshot()
app$setInputs(end_date = "2015-01-01")
app$snapshot()
